name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7', 'debug' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1

        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
